Ludum Dare 26 -- The Fair King

* Description

This project is a game that was originally released for the Ludum Dare
26 game Jam.  The original release of the game can be checked here:

http://www.ludumdare.com/compo/ludum-dare-26/?action=preview&uid=7847

The goal of the game is divide each of the screens so that each color
(except black and white) is equally distributed between the divisions.

The game uses the libGDX java library, and it is available for Desktop
and Android.

* Goals

My general goal for this project is to remove most of the interface
bugs and unintuitive behavior by the end of the month. If possible, I
would also like to improve the look of the game on Android a bit - it
looks too washed out.

* Task List
** DONE Improve stage selection logic
- [X] Remove the "click invisible stage" bug;
- [X] Rework the logic for opening new stages; 

** DONE Improve game interface
- [X] Move "line" to a separate class (same behavior)
- [X] Remove drawing timeout OR add timeout indicator; -- apparently, I can deal with pretty long lines
- [X] Game detects an incomplete line and cancel the line;
- [X] Game detects an "almost complete" line, and completes that line;

** TODO General Polish;
- [X] Add a version counter
- [X] Add a "clear data" button
- [ ] Make the level selection screen easier to navigate;
- [ ] Make buttons hit boxes larger;
- [ ] Make the game look less washed out on Android;
- [ ] Add some sort of marking for getting "A"s?
  
** TODO Make game easier to understand
- [X] Move level 6 later into the game;
- [ ] Add a "Level Unlocked" message;
- [ ] Improve the tutorial screens;
- [ ] Add some in-game explanation messages;
- [ ] Add "Select level" wording;
	
** TODO Other;
- [ ] Add to Play Store.
- [ ] Clear "Todo"s inside the code itself
- [ ] Comment each function
