Ludum Dare 26 -- The Fair King

* Description

This project is a game that was originally released for the Ludum Dare
26 game Jam.  The original release of the game can be checked here:

http://www.ludumdare.com/compo/ludum-dare-26/?action=preview&uid=7847

The goal of the game is divide each of the screens so that each color
(except black and white) is equally distributed between the divisions.

The game uses the libGDX java library, and it is available for Desktop
and Android.

* Goals

My general goal for this project is to remove most of the interface
bugs and unintuitive behavior by the end of the month. If possible, I
would also like to improve the look of the game on Android a bit - it
looks too washed out.

* Task List
** DONE Improve stage selection logic
- [X] Remove the "click invisible stage" bug;
- [X] Rework the logic for opening new stages; 

** DONE Improve game interface
- [X] Move "line" to a separate class (same behavior)
- [X] Remove drawing timeout OR add timeout indicator; -- apparently, I can deal with pretty long lines
- [X] Game detects an incomplete line and cancel the line;
- [X] Game detects an "almost complete" line, and completes that line;

** TODO General Polish;
- [X] Add a version counter
- [X] Add a "clear data" button
- [X] Make the level selection screen easier to navigate;
   X - navigation buttons should receive continuous clicks, and not "touch and click"
   X - navigation should stop when the last name is on the bottom, not the top
   - should navigate on swipe gestures
- [X] Make buttons hit boxes larger;
- [ ] Make the game look less washed out on Android;
  
** TODO Make game easier to understand
- [X] Move level 6 later into the game;
- [X] Improve the "score" screen
- [ ] Improve the tutorial screens;
  + Rewrite phrasing of screens 1 and 2
  + Add an HTML link for screen 3
	
** TODO Other;
- [ ] Add 1.1 to Play Store.
- [ ] Clear "Todo"s inside the code itself
- [ ] Comment each function

** TODO 1.2 Additions
- [ ] Add some in-game explanation messages;
  + What kind of messages?
- [ ] Add "Select level" wording;
  + Change Level selection screen to add an obvious "select level" message
- [ ] Add some marking on the "king" as you get more As
